title: The Tin Whiskers Band
description: The Bay Area's Best Southern Rock Jam Band

url: http://thetinwhiskers.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
future: true
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Song List
   url: /songs
 - title: Contact
   url: /contact

social:
   github: tinwhiskersband
   twitter: ttwbandca
   email: info@thetinwhiskers.com

google_analytics: "UA-58695840-3"
