title: The Tin Whiskers Band
description: The Bay Area's Best Southern Rock Jam Band

url: http://thetinwhiskers.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: tinwhiskersband
   twitter: ttwbandca
   facebook: thetinwhiskers
   email: info@thetinwhiskers.com

google_analytics: "UA-58695840-3"
